# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# For debugging zsh startup time
# zmodload zsh/zprof
# for i in $(seq 1 10); do /usr/bin/time $SHELL -i -c exit; done

function read_config {
  if [[ -e "$1" ]]; then
      . "$1"
  else echo Missing "$1"
  fi
}

function read_config_if_exists {
  [[ -e "$1" ]] && . "$1" && t_debug Read "$1"
}

# Re-use BASH aliases and exports
read_config "$HOME/.bash.d/core_utils.sh"
read_config ~/.bash.d/aliases_and_functions.sh
read_config ~/.zsh/zshenv.sh
read_config ~/.zsh/zshconf.zsh
read_config ~/.zsh/colors.zsh
read_config "$HOME/.bash.d/colors.sh"

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  read_config ~/.zplug/init.zsh && zplug update --self > /dev/null
else
    read_config ~/.zplug/init.zsh
fi

##################################################
## Based on zplug Example section
## https://github.com/zplug/zplug#example
##################################################

# Load completion library for those sweet [tab] squares
zplug "lib/completion", from:oh-my-zsh
zplug "plugins/colorize", from:oh-my-zsh
zplug "rupa/z", use:z.sh
# Syntax highlighting for commands, load last
zplug "chrissicool/zsh-256color", from:github
zplug "djui/alias-tips", from:github
zplug "zlsun/solarized-man", from:github
zplug "zsh-users/zsh-autosuggestions" # suggests commands as you type based on history and completions.
# zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
   printf "Install? [y/N]: "
   if read -r -q; then
       echo; zplug install
   fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# eval "$(starship init zsh)"
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# zprof

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if which jenv > /dev/null; then eval "$(jenv init -)"; fi
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
